/*
 *    Copyright 2018 Timothy J Veil
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package veil.hdp.hive.jdbc.bindings;


public enum TOperationType implements org.apache.thrift.TEnum {
  EXECUTE_STATEMENT(0),
  GET_TYPE_INFO(1),
  GET_CATALOGS(2),
  GET_SCHEMAS(3),
  GET_TABLES(4),
  GET_TABLE_TYPES(5),
  GET_COLUMNS(6),
  GET_FUNCTIONS(7),
  UNKNOWN(8);

  private final int value;

  private TOperationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TOperationType findByValue(int value) { 
    switch (value) {
      case 0:
        return EXECUTE_STATEMENT;
      case 1:
        return GET_TYPE_INFO;
      case 2:
        return GET_CATALOGS;
      case 3:
        return GET_SCHEMAS;
      case 4:
        return GET_TABLES;
      case 5:
        return GET_TABLE_TYPES;
      case 6:
        return GET_COLUMNS;
      case 7:
        return GET_FUNCTIONS;
      case 8:
        return UNKNOWN;
      default:
        return null;
    }
  }
}
