/*
 *    Copyright 2018 Timothy J Veil
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package veil.hdp.hive.jdbc.bindings;


public enum TOperationState implements org.apache.thrift.TEnum {
  INITIALIZED_STATE(0),
  RUNNING_STATE(1),
  FINISHED_STATE(2),
  CANCELED_STATE(3),
  CLOSED_STATE(4),
  ERROR_STATE(5),
  UKNOWN_STATE(6),
  PENDING_STATE(7),
  TIMEDOUT_STATE(8);

  private final int value;

  private TOperationState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TOperationState findByValue(int value) { 
    switch (value) {
      case 0:
        return INITIALIZED_STATE;
      case 1:
        return RUNNING_STATE;
      case 2:
        return FINISHED_STATE;
      case 3:
        return CANCELED_STATE;
      case 4:
        return CLOSED_STATE;
      case 5:
        return ERROR_STATE;
      case 6:
        return UKNOWN_STATE;
      case 7:
        return PENDING_STATE;
      case 8:
        return TIMEDOUT_STATE;
      default:
        return null;
    }
  }
}
