package veil.hdp.hive.jdbc;

import veil.hdp.hive.jdbc.HiveDriver;

import java.sql.*;

abstract class AbstractStatement implements Statement {
    @Override
    public final void setCursorName(String name) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final void addBatch(String sql) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final void clearBatch() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final int[] executeBatch() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final int executeUpdate(String sql, String[] columnNames) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final boolean execute(String sql, int[] columnIndexes) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final boolean execute(String sql, String[] columnNames) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final <T> T unwrap(Class<T> iface) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public final boolean isWrapperFor(Class<?> iface) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void close() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public int getMaxRows() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void cancel() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void clearWarnings() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public int getUpdateCount() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public int getFetchDirection() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public int getFetchSize() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public int getResultSetType() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public Connection getConnection() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public boolean isClosed() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public boolean isPoolable() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        throw HiveDriver.notImplemented(this.getClass());
    }

}
